version: '3.3'

services:

  web:
    build: .
    command: >
      sh -c "sleep 10s; 
      python manage.py migrate; 
      python manage.py update_db;
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:5.7.40
    ports:
      - 3306:3306
    restart: always
    environment:
      - "MYSQL_DATABASE=flashfire"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=user"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - flashfire:/var/lib/mysql
      
volumes:
  flashfire:
