# Generated by Django 4.1.4 on 2022-12-31 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('size', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='size',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='stock_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.stock'),
            preserve_default=False,
        ),
    ]
