# Generated by Django 4.1.5 on 2023-02-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_password',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='account_username',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='accrued_cash',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='available_funds',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='buying_power',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='cushion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='equity_with_loan_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='excess_liquidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='full_available_funds',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='full_excess_liquidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='full_init_margin_req',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='full_main_t_margin_req',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gross_position_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='init_margin_req',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='look_ahead_available_funds',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='look_ahead_excess_liquidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='look_ahead_init_margin_req',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='look_ahead_main_t_margin_req',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='look_ahead_next_change',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='main_t_margin_req',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='net_liquidation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_cash_value',
            field=models.FloatField(null=True),
        ),
    ]
