# Generated by Django 4.1.5 on 2023-01-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='ask',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='ask_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='average_daily_volume_10_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='average_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='average_volume_10_days',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='bid',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='currency',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='day_high',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='day_low',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='exchange_timezone_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='fifty_day_average',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='fifty_two_week_high',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='fifty_two_week_low',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='long_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='market',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='market_cap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='open_price',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='previous_close',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='regular_market_day_high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='regular_market_day_low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='regular_market_previous_close',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='regular_market_volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='sector',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='short_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
