# Generated by Django 4.1.5 on 2023-01-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_stockinfo_ask_alter_stockinfo_ask_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='ask_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='market_cap',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='sector',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
