# Generated by Django 4.1.5 on 2023-09-24 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_watchlist_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='account_id',
            new_name='user_id',
        ),
    ]
