# Generated by Django 4.1.5 on 2023-01-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stockinfo_stockpriceminute_delete_latesttrade'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table='stocks',
        ),
    ]
