# Generated by Django 4.1.5 on 2023-01-04 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_stock_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table=None,
        ),
    ]
