# Generated by Django 4.1.5 on 2023-01-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stockinfo_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
