# Generated by Django 4.1.5 on 2023-09-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_watchlist_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('watchlist_id', 'stock_id')},
        ),
    ]
