# Generated by Django 4.1.5 on 2023-01-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_stock_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='_52_week_change',
            field=models.DecimalField(decimal_places=7, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='address1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='bid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='bid_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='book_value',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='company_officers',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='current_ratio',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='date_short_interest',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='day_high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='debt_to_equity',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='dividend_yield',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='earnings_growth',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='earnings_quarterly_growth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='ebitda',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='ebitda_margins',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='enterprise_to_ebitda',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='enterprise_to_revenue',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='enterprise_value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='exchange',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='exchange_timezone_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='exchange_timezone_short_name',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='fax',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='financial_currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='float_shares',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='forward_eps',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='forward_pe',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='free_cashflow',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='full_time_employees',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='gmt_offset_milliseconds',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='gross_margins',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='gross_profits',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='held_percent_insiders',
            field=models.DecimalField(decimal_places=5, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='held_percent_institutions',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='implied_shares_outstanding',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='industry',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='is_esg_populated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='last_dividend_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='last_dividend_value',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='last_fiscal_year_end',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='last_split_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='last_split_factor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='logo_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='long_business_summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='market',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='max_age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='message_board_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='most_recent_quarter',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='net_income_to_common',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='next_fiscal_year_end',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='number_of_analyst_opinions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='operating_cashflow',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='operating_margins',
            field=models.DecimalField(decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='payout_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='peg_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='previous_close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='price_hint',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='price_to_book',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='price_to_sales_trailing_12_months',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='profit_margins',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='quick_ratio',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='quote_type',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='recommendation_key',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='recommendation_mean',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='regular_market_open',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='regular_market_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='return_on_assets',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='return_on_equity',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='revenue_growth',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='revenue_per_share',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='sandp_52_week_change',
            field=models.DecimalField(decimal_places=7, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='sector',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='shares_outstanding',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='shares_percent_shares_out',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='shares_short',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='shares_short_previous_month_date',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='shares_short_prior_month',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='short_percent_of_float',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='short_ratio',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='target_high_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='target_low_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='target_mean_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='target_median_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='total_cash',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='total_cash_per_share',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='total_debt',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='total_revenue',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='tradeable',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='trailing_annual_dividend_yield',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='trailing_eps',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='trailing_peg_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='two_hundred_day_average',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
