# Generated by Django 4.1.5 on 2023-01-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_stockinfo__52_week_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinfo',
            old_name='open',
            new_name='open_price',
        ),
        migrations.RenameField(
            model_name='stockinfo',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
