# Generated by Django 4.1.5 on 2023-01-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_open_stockinfo_open_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='company_officers',
        ),
    ]
