# Generated by Django 4.1.5 on 2023-01-12 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_datetime_stockhistory_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='symbol',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='stockinfo',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
