# Generated by Django 4.1.5 on 2023-01-12 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_symbol_stockhistory_stock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
