# Generated by Django 4.1.5 on 2023-01-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_stockinfo_company_officers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinfo',
            old_name='long_business_summary',
            new_name='longBusinessSummary',
        ),
    ]
