# Generated by Django 4.1.5 on 2023-01-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_long_business_summary_stockinfo_longbusinesssummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinfo',
            old_name='max_age',
            new_name='maxAge',
        ),
    ]
