# Generated by Django 4.1.5 on 2023-01-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
