# Generated by Django 4.1.5 on 2023-01-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_stockhistory_close_alter_stockhistory_high_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='date',
            new_name='timestamp',
        ),
    ]
