# Generated by Django 4.1.5 on 2023-01-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_annual_holdings_turnover_stockinfo_annualholdingsturnover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='address2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
