# Generated by Django 4.1.5 on 2023-01-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_stockinfo_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='currentRatio',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
