# Generated by Django 4.1.5 on 2023-01-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_timestamp_stockhistory_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='openinterest',
        ),
    ]
