# Generated by Django 4.1.5 on 2023-01-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_stockhistory_openinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='long_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='operating_margins',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='revenue_growth',
            field=models.FloatField(null=True),
        ),
    ]
