# Generated by Django 4.1.5 on 2023-01-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_stockinfo_quickratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='debtToEquity',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
