# Generated by Django 4.1.5 on 2023-01-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_stockinfo_country_alter_stockinfo_long_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='datetime',
            field=models.DateField(),
        ),
    ]
