# Generated by Django 4.1.5 on 2023-01-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_stockhistory_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='datetime',
            new_name='date',
        ),
    ]
