# Generated by Django 4.1.5 on 2023-01-29 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_rename_datetime_stockhistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='stock_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.CharField(default='wl', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
