# Generated by Django 4.1.5 on 2023-01-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_stockinfo_dateshortinterest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='beta',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
    ]
