# Generated by Django 4.1.5 on 2023-01-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_stockinfo_beta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
