# Generated by Django 4.1.5 on 2023-01-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_stockinfo_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='operatingMargins',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='returnOnEquity',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='revenueGrowth',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
