# Generated by Django 4.1.5 on 2023-02-09 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_user_remove_watchliststock_stock_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('AccountType', models.CharField(max_length=20)),
                ('Cushion', models.SmallIntegerField()),
                ('LookAheadNextChange', models.IntegerField()),
                ('AccruedCash', models.FloatField()),
                ('AvailableFunds', models.FloatField()),
                ('BuyingPower', models.FloatField()),
                ('EquityWithLoanValue', models.FloatField()),
                ('ExcessLiquidity', models.FloatField()),
                ('FullAvailableFunds', models.FloatField()),
                ('FullExcessLiquidity', models.FloatField()),
                ('FullInitMarginReq', models.FloatField()),
                ('FullMaintMarginReq', models.FloatField()),
                ('GrossPositionValue', models.FloatField()),
                ('InitMarginReq', models.FloatField()),
                ('LookAheadAvailableFunds', models.FloatField()),
                ('LookAheadExcessLiquidity', models.FloatField()),
                ('LookAheadInitMarginReq', models.FloatField()),
                ('LookAheadMaintMarginReq', models.FloatField()),
                ('MaintMarginReq', models.FloatField()),
                ('NetLiquidation', models.FloatField()),
                ('TotalCashValue', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='account_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='core.account'),
            preserve_default=False,
        ),
    ]
