# Generated by Django 4.1.5 on 2023-01-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_stockinfo_operatingmargins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='annualHoldingsTurnover',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='annualReportExpenseRatio',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='beta',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='beta3Year',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='bookValue',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='currentPrice',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='currentRatio',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='debtToEquity',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='earningsGrowth',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='ebitdaMargins',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='enterpriseToEbitda',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='enterpriseToRevenue',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='exchange',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='exchangeTimezoneShortName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='fiftyTwoWeekChange',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='financialCurrency',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='forwardEps',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='grossMargins',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='heldPercentInsiders',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='heldPercentInstitutions',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='lastDividendValue',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='longName',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='priceToBook',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='profitMargins',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='quickRatio',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='quoteType',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='recommendationMean',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='returnOnAssets',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='returnOnEquity',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='revenuePerShare',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='revenueQuarterlyGrowth',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='sandp52WeekChange',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='sharesPercentSharesOut',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='shortRatio',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='targetHighPrice',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='targetLowPrice',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='targetMeanPrice',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='targetMedianPrice',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='totalCashPerShare',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='totalYield',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='trailingEps',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
