# Generated by Django 4.1.5 on 2023-02-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_account_delete_user_remove_watchlist_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched', to='core.stockinfo')),
                ('watchlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.watchlist')),
            ],
        ),
    ]
