# Generated by Django 4.1.5 on 2023-01-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_stockinfo_address2_remove_stockinfo_algorithm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='lastDividendValue',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='trailingPE',
        ),
    ]
