# Generated by Django 4.1.5 on 2023-02-09 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_account_last_updated_watchlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.account', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.account', unique=True)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='core.stockinfo')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='core.transactionhistory')),
            ],
        ),
    ]
