# Generated by Django 4.1.5 on 2023-02-09 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_transactionhistory_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='position',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.account'),
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
