# Generated by Django 4.1.5 on 2023-02-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_account_cushion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='AccountType',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='AccruedCash',
            new_name='accrued_cash',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='AvailableFunds',
            new_name='available_funds',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='BuyingPower',
            new_name='buying_power',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Cushion',
            new_name='cushion',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='EquityWithLoanValue',
            new_name='equity_with_loan_value',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='ExcessLiquidity',
            new_name='excess_liquidity',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='FullAvailableFunds',
            new_name='full_available_funds',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='FullExcessLiquidity',
            new_name='full_excess_liquidity',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='FullInitMarginReq',
            new_name='full_init_margin_req',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='FullMaintMarginReq',
            new_name='full_main_t_margin_req',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='GrossPositionValue',
            new_name='gross_position_value',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='InitMarginReq',
            new_name='init_margin_req',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='LookAheadAvailableFunds',
            new_name='look_ahead_available_funds',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='LookAheadExcessLiquidity',
            new_name='look_ahead_excess_liquidity',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='LookAheadInitMarginReq',
            new_name='look_ahead_init_margin_req',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='LookAheadMaintMarginReq',
            new_name='look_ahead_maint_margin_req',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='LookAheadNextChange',
            new_name='look_ahead_next_change',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='MaintMarginReq',
            new_name='main_t_margin_req',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='NetLiquidation',
            new_name='net_liquidation',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='TotalCashValue',
            new_name='total_cash_value',
        ),
    ]
