# Generated by Django 4.1.5 on 2023-02-11 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_accounttype_account_account_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='look_ahead_maint_margin_req',
            new_name='look_ahead_main_t_margin_req',
        ),
    ]
