from django.db import models

# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    cash = models.DecimalField(default=0.00, decimal_places=2, max_digits=15)


class Stock(models.Model):
    symbol = models.CharField(max_length=255, unique=True)
    company = models.CharField(max_length=255)
    exchange = models.CharField(max_length=255)

class StockPriceMinute(models.Model):
    open = models.DecimalField(default=0.00, decimal_places=2, max_digits=15)
    high = models.DecimalField(default=0.00, decimal_places=2, max_digits=15)
    low = models.DecimalField(default=0.00, decimal_places=2, max_digits=15)
    close = models.DecimalField(default=0.00, decimal_places=2, max_digits=15)
    volume = models.DecimalField(default=0.00, decimal_places=2, max_digits=15)
    datetime = models.DateTimeField(auto_now_add=True)

class WatchList(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="watchlist")
    stock_id = models.ForeignKey(Stock, on_delete=models.CASCADE, related_name="watchlist")


class StockHistory(models.Model):
    stock_id = models.ForeignKey(Stock, on_delete=models.CASCADE, related_name="history") 



class StockInfo(models.Model):
    zip = models.CharField(max_length=10, null=True)
    sector = models.CharField(max_length=50, null=True)
    full_time_employees = models.PositiveIntegerField(null=True)
    long_business_summary = models.TextField(null=True)
    city = models.CharField(max_length=50, null=True)
    phone = models.CharField(max_length=20, null=True)
    state = models.CharField(max_length=20, null=True)
    country = models.CharField(max_length=50, null=True)
    company_officers = models.TextField(null=True)
    website = models.URLField(null=True)
    max_age = models.PositiveIntegerField(null=True)
    address1 = models.CharField(max_length=100, null=True)
    fax = models.CharField(max_length=20, null=True)
    industry = models.CharField(max_length=50, null=True)
    ebitda_margins = models.DecimalField(max_digits=5, decimal_places=4, null=True)
    profit_margins = models.DecimalField(max_digits=5, decimal_places=4, null=True)
    gross_margins = models.DecimalField(max_digits=5, decimal_places=4, null=True)
    operating_cashflow = models.BigIntegerField(null=True)
    revenue_growth = models.DecimalField(max_digits=5, decimal_places=4, null=True)
    operating_margins = models.DecimalField(max_digits=7, decimal_places=6, null=True)
    ebitda = models.BigIntegerField(null=True)
    target_low_price = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    recommendation_key = models.CharField(max_length=10, null=True)
    gross_profits = models.BigIntegerField(null=True)
    free_cashflow = models.BigIntegerField(null=True)
    target_median_price = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    current_price = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    earnings_growth = models.DecimalField(max_digits=5, decimal_places=4, null=True)
    current_ratio = models.DecimalField(max_digits=5, decimal_places=4, null=True)
    return_on_assets = models.DecimalField(max_digits=5, decimal_places=4, null=True)
    number_of_analyst_opinions = models.PositiveIntegerField(null=True)
    target_mean_price = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    debt_to_equity = models.DecimalField(max_digits=6, decimal_places=4, null=True)
    return_on_equity = models.DecimalField(max_digits=5, decimal_places=4, null=True)
    target_high_price = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    total_cash = models.BigIntegerField(null=True)
    total_debt = models.BigIntegerField(null=True)
    total_revenue = models.BigIntegerField(null=True)
    total_cash_per_share = models.DecimalField(max_digits=6, decimal_places=3, null=True)
    financial_currency = models.CharField(max_length=3, null=True)
    revenue_per_share = models.DecimalField(max_digits=6, decimal_places=3, null=True)
    quick_ratio = models.DecimalField(max_digits=4, decimal_places=3, null=True)
    recommendation_mean = models.DecimalField(max_digits=4, decimal_places=1, null=True)
    exchange = models.CharField(max_length=3, null=True)
    short_name = models.CharField(max_length=50)
    long_name = models.CharField(max_length=50)
    exchange_timezone_name = models.CharField(max_length=50, null=True)
    exchange_timezone_short_name = models.CharField(max_length=5, null=True)
    is_esg_populated = models.BooleanField(null=True)
    gmt_offset_milliseconds = models.CharField(max_length=10, null=True)
    quote_type = models.CharField(max_length=6, null=True)
    symbol = models.CharField(max_length=10, unique=True)
    message_board_id = models.CharField(max_length=20, null=True)
    market = models.CharField(max_length=20, null=True)
    annual_holdings_turnover = models.DecimalField(max_digits=6, decimal_places=5, null=True)
    enterprise_to_revenue = models.DecimalField(max_digits=6, decimal_places=3, null=True)
    beta_3_year = models.DecimalField(max_digits=6, decimal_places=5, null=True)
    enterprise_to_ebitda = models.DecimalField(max_digits=6, decimal_places=3, null=True)
    _52_week_change = models.DecimalField(max_digits=8, decimal_places=7, null=True)
    morning_star_risk_rating = models.PositiveSmallIntegerField(null=True)
    forward_eps = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    revenue_quarterly_growth = models.DecimalField(max_digits=6, decimal_places=5, null=True)
    shares_outstanding = models.BigIntegerField(null=True)
    fund_inception_date = models.DateField(null=True)
    annual_report_expense_ratio = models.DecimalField(max_digits=6, decimal_places=5, null=True)
    total_assets = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    book_value = models.DecimalField(max_digits=7, decimal_places=3, null=True)
    shares_short = models.BigIntegerField(null=True)
    shares_percent_shares_out = models.DecimalField(max_digits=6, decimal_places=4, null=True)
    fund_family = models.CharField(max_length=50, null=True)
    last_fiscal_year_end = models.PositiveIntegerField(null=True)
    held_percent_institutions = models.DecimalField(max_digits=6, decimal_places=5, null=True)
    net_income_to_common = models.BigIntegerField(null=True)
    trailing_eps = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    last_dividend_value = models.DecimalField(max_digits=4, decimal_places=2, null=True)
    sandp_52_week_change = models.DecimalField(max_digits=8, decimal_places=7, null=True)
    price_to_book = models.DecimalField(max_digits=8, decimal_places=5, null=True)
    held_percent_insiders = models.DecimalField(max_digits=7, decimal_places=5, null=True)
    next_fiscal_year_end = models.PositiveIntegerField(null=True)
    total_yield = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    most_recent_quarter = models.PositiveIntegerField(null=True)
    short_ratio = models.DecimalField(max_digits=4, decimal_places=1, null=True)
    shares_short_previous_month_date = models.PositiveIntegerField(null=True)
    float_shares = models.BigIntegerField(null=True)
    beta = models.DecimalField(max_digits=6, decimal_places=5)
    enterprise_value = models.BigIntegerField(null=True)
    price_hint = models.SmallIntegerField(null=True)
    three_year_average_return = models.FloatField(blank=True, null=True)
    last_split_date = models.DateField(null=True)
    last_split_factor = models.CharField(max_length=10, null=True)
    legal_type = models.CharField(max_length=50, blank=True, null=True)
    last_dividend_date = models.DateField(null=True)
    morning_star_overall_rating = models.FloatField(blank=True, null=True)
    earnings_quarterly_growth = models.FloatField(null=True)
    price_to_sales_trailing_12_months = models.FloatField(null=True)
    date_short_interest = models.DateField(null=True)
    peg_ratio = models.FloatField(null=True)
    ytd_return = models.FloatField(blank=True, null=True)
    forward_pe = models.FloatField(null=True)
    last_cap_gain = models.FloatField(blank=True, null=True)
    short_percent_of_float = models.FloatField(null=True)
    shares_short_prior_month = models.BigIntegerField(null=True)
    implied_shares_outstanding = models.BigIntegerField(null=True)
    category = models.CharField(max_length=50, blank=True, null=True)
    five_year_average_return = models.FloatField(blank=True, null=True)
    previous_close = models.FloatField(null=True)
    regular_market_open = models.FloatField(null=True)
    two_hundred_day_average = models.FloatField(null=True)
    trailing_annual_dividend_yield = models.FloatField(null=True)
    payout_ratio = models.FloatField(null=True)
    volume24Hr = models.CharField(max_length=50, null=True)
    regularMarketDayHigh = models.CharField(max_length=50, null=True)
    navPrice = models.CharField(max_length=50, null=True)
    averageDailyVolume10Day = models.CharField(max_length=50, null=True)
    regularMarketPreviousClose = models.CharField(max_length=50, null=True)
    fiftyDayAverage = models.CharField(max_length=50, null=True)
    trailingAnnualDividendRate = models.CharField(max_length=50, null=True)
    open = models.CharField(max_length=50, null=True)
    toCurrency = models.CharField(max_length=50, null=True)
    averageVolume10days = models.CharField(max_length=50, null=True)
    expireDate = models.CharField(max_length=50, null=True)
    algorithm = models.CharField(max_length=50, null=True)
    dividendRate = models.CharField(max_length=50, null=True)
    exDividendDate = models.CharField(max_length=50, null=True)
    circulatingSupply = models.CharField(max_length=50, null=True)
    startDate = models.CharField(max_length=50, null=True)
    regularMarketDayLow = models.CharField(max_length=50, null=True)
    currency = models.CharField(max_length=50, null=True)
    trailingPE = models.CharField(max_length=50, null=True)
    regularMarketVolume = models.CharField(max_length=50, null=True)
    lastMarket = models.CharField(max_length=50, null=True)
    maxSupply = models.CharField(max_length=50, null=True)
    openInterest = models.CharField(max_length=50, null=True)
    marketCap = models.CharField(max_length=50, null=True)
    volumeAllCurrencies = models.CharField(max_length=50, null=True)
    strikePrice = models.CharField(max_length=50, null=True)
    averageVolume = models.CharField(max_length=50, null=True)
    dayLow = models.CharField(max_length=50, null=True)
    ask = models.CharField(max_length=50, null=True)
    askSize = models.CharField(max_length=50, null=True)
    volume = models.CharField(max_length=50, null=True)
    fiftyTwoWeekHigh = models.CharField(max_length=50, null=True)
    fromCurrency = models.CharField(max_length=50, null=True)
    fiveYearAvgDividendYield = models.CharField(max_length=50, null=True)
    fiftyTwoWeekLow = models.CharField(max_length=50, null=True)
    bid = models.FloatField(null=True)
    tradeable = models.BooleanField(null=True)
    dividend_yield = models.FloatField(null=True)
    bid_size = models.IntegerField(null=True)
    day_high = models.FloatField(null=True)
    coin_market_cap_link = models.URLField(null=True)
    regular_market_price = models.FloatField(null=True)
    pre_market_price = models.FloatField(null=True)
    logo_url = models.URLField(null=True)
    trailing_peg_ratio = models.FloatField(null=True)